{
 "title": "YOUTUBE TRENDING",
 "time": { "from": "2021-11-15T17:00:00.000Z", "to": "2021-11-25T16:59:59.000Z" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "country",
    "query": "select distinct country_code from country_list"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(video_id) as videos, sum(view_count) as views, sum(likes) as likes, sum(dislikes) as dislikes, sum(comment_count) as comments from\n(\nselect distinct on (video_id) video_id, runtime, view_count, likes, dislikes,comment_count\nfrom vn_ytb_trending\nWHERE country_code = '$country'\norder by video_id, runtime desc) t"
    }
   ]
  },
  { "title": "OVERVIEW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Realtime stats",
   "type": "stat",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select\n  count(video_id) as videos,\n  sum(view_count) as views,\n  sum(likes) as likes,\n  sum(dislikes) as dislikes,\n  sum(comment_count) as comments\nfrom\n(\nselect distinct on (video_id)\n  video_id, runtime,\n  view_count,\n  likes,\n  dislikes,\n  comment_count,\n  channel_title\nfrom vn_ytb_trending\nwhere $__timeFilter(runtime) and country_code = '$country'\norder by video_id, runtime desc) t"
    }
   ]
  },
  {
   "title": "No.of videos of each category",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 17, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select video_category, count(*) as ct from (\n\tselect distinct on (video_id)\n\truntime,\n\tvideo_id, video_category\n\tfrom\n\t(\n\t\tSELECT a.runtime, a.video_id, b.video_category, a.country_code\n\t\tFROM vn_ytb_trending as a\n\t\tINNER JOIN video_categories as b ON a.category_id=b.category_id\n\t) u\n\twhere $__timeFilter(runtime) and u.country_code = '$country'\n) t\ngroup by 1"
    }
   ]
  },
  {
   "title": "No.of views of each category",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(view_count), video_category from\n(\nselect distinct on (video_id) video_id, runtime, video_category, view_count\nfrom\n\t(\n\t\tSELECT a.runtime, a.video_id, b.video_category, a.view_count, a.country_code\n\t\tFROM vn_ytb_trending as a\n\t\tINNER JOIN video_categories as b ON a.category_id=b.category_id\n\t) u\nwhere $__timeFilter(runtime) and u.country_code = '$country'\norder by video_id, runtime desc) t\ngroup by video_category"
    }
   ]
  },
  {
   "title": "No.of likes, dislikes, comments of each category",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "select sum(likes) as likes, sum(dislikes) as dislikes, sum(comment_count) as comment_count, video_category from\n(\nselect distinct on (video_id) video_id, runtime, video_category, likes, dislikes, comment_count\nfrom\n\t(\n\t\tSELECT a.runtime, a.video_id, b.video_category, a.likes, a.dislikes, a.comment_count, a.country_code\n\t\tFROM vn_ytb_trending as a\n\t\tINNER JOIN video_categories as b ON a.category_id=b.category_id\n\t) u\nwhere $__timeFilter(runtime) and u.country_code = '$country'\norder by video_id, runtime desc) t\ngroup by video_category"
    }
   ]
  },
  { "title": "TOP10 TRENDING", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "List top 10 trending",
   "type": "table",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT\n\tvn_ytb_trending.title,\n\tvn_ytb_trending.channel_title,\n\tvideo_categories.video_category,\n\tvn_ytb_trending.trending_id\nFROM vn_ytb_trending\nINNER JOIN video_categories ON vn_ytb_trending.category_id=video_categories.category_id\nWHERE $__timeFilter(runtime) and country_code = '$country'\nORDER BY vn_ytb_trending.runtime DESC,vn_ytb_trending.trending_id ASC\nlimit 10"
    }
   ]
  },
  {
   "title": "No.of videos of each channel",
   "type": "stat",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select a.channel_title, b.ct\r\nfrom\r\n(\r\n\tselect channel_title, trending_id\r\n\t\tfrom vn_ytb_trending\r\n\t\tWHERE $__timeFilter(runtime) and country_code = '$country'\r\n\t\tORDER BY vn_ytb_trending.runtime DESC,vn_ytb_trending.trending_id ASC\r\n\t\tlimit 10\r\n) a\r\ninner join\r\n(select channel_title, count(*) as ct from (\r\n\tselect distinct on (video_id)\r\n\tchannel_title\r\n\tfrom vn_ytb_trending\r\n\twhere channel_title in\r\n\t(\r\n\t\tselect channel_title\r\n\t\tfrom vn_ytb_trending\r\n\t\tWHERE $__timeFilter(runtime) and country_code = '$country'\r\n\t\tORDER BY vn_ytb_trending.runtime DESC,vn_ytb_trending.trending_id ASC\r\n\t\tlimit 10\r\n\t)\r\n\tand $__timeFilter(runtime) and country_code = '$country'\r\n) t\r\ngroup by 1) b \r\nON a.channel_title=b.channel_title\r\norder by a.trending_id asc"
    }
   ]
  },
  {
   "title": "Number of views",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  runtime AS \"time\",\n  title AS metric,\n  view_count\nFROM vn_ytb_trending\nWHERE\n  $__timeFilter(runtime) and country_code = '$country'\nORDER BY runtime DESC,vn_ytb_trending.trending_id ASC\nLIMIT 10"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "rawSql": "select runtime as \"time\", title, view_count as \" \"\nfrom vn_ytb_trending\nwhere title\nin\n(\n\tselect distinct(title)\n\tfrom\n\t(\n\t\tSELECT runtime, title, trending_id, view_count\n\t\tFROM vn_ytb_trending\n\t\twhere $__timeFilter(runtime) and country_code = '$country'\n\t\tORDER BY runtime DESC, trending_id ASC\n\t\tLIMIT 10\n) t\n)\norder by runtime asc, view_count, title asc"
    }
   ]
  },
  {
   "title": "No.of likes, dislikes, comment_count",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "rawSql": "SELECT\n  runtime AS \"time\",\n  title AS metric,\n  likes,\n  dislikes,\n  comment_count\nFROM vn_ytb_trending\nWHERE\n  $__timeFilter(runtime) and country_code = '$country'\nORDER BY runtime DESC, vn_ytb_trending.trending_id ASC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "No.of hours on trending",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 15, "x": 0, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select a.title, b.no_of_hour_on_trending\nfrom\n(\n\tSELECT title, trending_id, runtime\n\tFROM vn_ytb_trending\n\tWHERE $__timeFilter(runtime) and country_code = '$country'\n\tand trending_id < 11\n\torder by runtime DESC, trending_id ASC\n\tlimit 10\n) a\ninner join\n(\n\tselect title, count(*) as no_of_hour_on_trending\n\tfrom\n\t(\n\t\tSELECT title, trending_id, runtime\n\t\tFROM vn_ytb_trending\n\t  WHERE runtime < $__timeTo()\n\t\tand trending_id < 11 and country_code = '$country'\n\t) t\n\twhere title in\n\t(\n\t\tselect title from\n\t\t(\n\t\t\tSELECT title, trending_id, runtime\n\t\t\tFROM vn_ytb_trending\n\t\t\tWHERE $__timeFilter(runtime) and country_code = '$country'\n\t\t\tand trending_id < 11\n\t\t\torder by runtime DESC, trending_id ASC\n\t\t\tlimit 10\n\t\t) c\n\t)\n\tgroup by title\n) b\nON a.title=b.title\norder by a.trending_id asc"
    }
   ]
  },
  {
   "title": "No.of videos corresponding to each category",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select video_category, count(*) as ct from (\n\tselect distinct on (video_id)\n\truntime,\n\tvideo_id, video_category\n\tfrom\n\t(\n\t\tselect a.runtime, a.video_id, b.video_category, a.country_code\n\t\tfrom\n\t\t(\n\t\t\tSELECT\n\t\t\t  runtime, category_id, video_id, trending_id, country_code\n\t\t\tFROM vn_ytb_trending\n\t\t\tWHERE trending_id < 11\n\t\t) a\n\t\tINNER JOIN video_categories as b ON a.category_id=b.category_id\n\t) c\n\twhere $__timeFilter(runtime) and c.country_code = '$country'\n) t\ngroup by 1"
    }
   ]
  }
 ]
}